// Pools of fake data used by anonymize.mjs.
// Everything here is invented. No mapping to real people.

export const FIRST_NAMES = [
  'Joe',
  'Maya',
  'Liam',
  'Ava',
  'Noah',
  'Emma',
  'Oliver',
  'Mia',
  'Lucas',
  'Zoe',
  'Ethan',
  'Lily',
  'Mason',
  'Ella',
  'Logan',
  'Aria',
  'Jacob',
  'Nora',
  'Aiden',
  'Hazel',
  'Daniel',
  'Ruby',
  'Henry',
  'Stella',
  'Owen',
  'Iris',
  'Leo',
  'Chloe',
  'Sam',
  'Grace',
  'Max',
  'Sofia',
  'Felix',
  'Layla',
  'Theo',
  'Ivy',
  'Eli',
  'Hannah',
  'Caleb',
  'Nina',
  'Jonas',
  'Maja',
  'Erik',
  'Sara',
  'Olav',
  'Saga',
  'Linus',
  'Freja',
  'Tobias',
  'Astrid',
  'Mikael',
  'Elin',
  'Anders',
  'Linnea',
  'Johan',
  'Hedda',
  'Gustav',
  'Tilde',
  'Kalle',
  'Vera',
  'Ravi',
  'Anika',
  'Aarav',
  'Diya',
  'Rohan',
  'Priya',
  'Karan',
  'Riya',
  'Vikram',
  'Sana',
  'Hiro',
  'Yuki',
  'Kenji',
  'Aiko',
  'Wei',
  'Mei',
  'Jian',
  'Lin',
  'Ming',
  'Hui',
  'Diego',
  'Lucia',
  'Mateo',
  'Camila',
  'Pablo',
  'Valeria',
  'Andres',
  'Renata',
  'Carlos',
  'Paula',
  'Amir',
  'Layan',
  'Omar',
  'Salma',
  'Yusuf',
  'Nour',
  'Khalid',
  'Dana',
  'Tariq',
  'Hala',
];

export const LAST_NAMES = [
  'Smith',
  'Johnson',
  'Brown',
  'Taylor',
  'Anderson',
  'Thomas',
  'Jackson',
  'White',
  'Harris',
  'Martin',
  'Garcia',
  'Martinez',
  'Robinson',
  'Clark',
  'Rodriguez',
  'Lewis',
  'Lee',
  'Walker',
  'Hall',
  'Allen',
  'Young',
  'King',
  'Wright',
  'Lopez',
  'Hill',
  'Scott',
  'Green',
  'Adams',
  'Baker',
  'Nelson',
  'Carter',
  'Mitchell',
  'Perez',
  'Roberts',
  'Turner',
  'Phillips',
  'Campbell',
  'Parker',
  'Evans',
  'Edwards',
  'Lindberg',
  'Bergström',
  'Sandberg',
  'Holm',
  'Lundgren',
  'Ekström',
  'Forsberg',
  'Sjöberg',
  'Åkesson',
  'Öhman',
  'Hansen',
  'Larsen',
  'Olsen',
  'Nielsen',
  'Sørensen',
  'Pedersen',
  'Mortensen',
  'Madsen',
  'Kristensen',
  'Knudsen',
  'Patel',
  'Sharma',
  'Singh',
  'Kumar',
  'Verma',
  'Reddy',
  'Iyer',
  'Mehta',
  'Joshi',
  'Kapoor',
  'Tanaka',
  'Suzuki',
  'Sato',
  'Takahashi',
  'Watanabe',
  'Yamamoto',
  'Nakamura',
  'Kobayashi',
  'Yoshida',
  'Yamada',
  'Silva',
  'Souza',
  'Ferreira',
  'Ribeiro',
  'Almeida',
  'Costa',
  'Pereira',
  'Oliveira',
  'Carvalho',
  'Rocha',
  'Haddad',
  'Khoury',
  'Najjar',
  'Hakim',
  'Saad',
  'Rahman',
  'Karim',
  'Aziz',
  'Mansour',
  'Farah',
];

// Short, varied message-style content. Some include emoji, quotes, multi-line.
export const FAKE_MESSAGES = [
  'Sounds good, talk soon!',
  'Thanks for the intro 🙏',
  'Can we move our call to tomorrow at 3?',
  'Just shared the doc — let me know what you think.',
  'Happy birthday! 🎉',
  'Yes, I am still in town until Friday.',
  'No worries, take your time.',
  'Great meeting you at the conference!',
  'I will get back to you by EOD.',
  'Coffee next week? My calendar is open Tue/Thu.',
  'Quick question: do you have the slide deck handy?',
  'Welcome to the team! 🚀',
  'Pls ignore my earlier message — wrong thread.',
  'Sure, ping me when you are ready.',
  'Lunch sometime? I am usually in the city on Wednesdays.',
  'Just landed. Will reply properly tomorrow.',
  'Congrats on the new role! Well deserved.',
  'Heads up: the meeting room changed to 4B.',
  'Mind if I share your post with my team?',
  'Yes — let us aim for early January then.',
  'Can you send me the PR link?',
  'Loved the talk. Where can I read more?',
  '👍 thanks!',
  'Apologies for the delay on my end.',
  'I am out next week, will follow up after.',
  'Could you forward the invite to my personal email?',
  'On it 👀',
  'That works for me. Sending the invite now.',
  'Thursdays usually work best for me.',
  'Let me check with the team and circle back.',
  'Just FYI — I will be working remotely this week.',
  'See you Monday!',
  'No problem at all. I will ping you next time I am around.',
  'Could you point me to whoever handles platform onboarding?',
  'Awesome talk yesterday 👏',
  'Forwarded — should land in your inbox shortly.',
  'Hi, I noticed your post on reliability — really resonated.',
  'Quick favor: can you take a look at this draft?',
  'I will be there. Bringing a colleague along too.',
  'Cool, let us sync next week then.',
  // Multi-line with quotes
  'A few thoughts inline:\n- the first option is simpler\n- the second one scales better\nLeaning toward option 2.',
  'She said "we should ship it" and honestly I agree.',
  // With commas + quotes mix
  'Tomorrow works, "any time after 10" as you said earlier.',
  'Thanks — added you to the channel. Welcome aboard!',
  'I am not sure, let me double-check and revert.',
  'Done ✅ — let me know if anything else is needed.',
];

export const FAKE_COMMENTS = [
  'Great post — really enjoyed the framing here. 👏',
  'Strong take. I would add that culture eats process for breakfast.',
  'Saving this one. Lots to unpack.',
  'Have you considered the trade-off with team autonomy?',
  '+1 — we have seen similar patterns at our org.',
  // Multi-line + quote
  'Two thoughts:\n1. The diagram is gold.\n2. "Boring tech wins" is underrated.\nThanks for sharing.',
  'Curious — how do you measure success on this?',
  'Spot on. The biggest gap is usually leadership awareness, not tools.',
  'Love this. Reminds me of the talk on platform thinking from last year.',
  '🔥 this is the post I needed today.',
  'I respectfully disagree on the third point — happy to discuss offline.',
  'Bookmarked. Will share with my team tomorrow.',
  'Excellent illustration. Mind if I reference it in a workshop?',
  'This is the kind of nuance that gets lost in most threads.',
  'Beautifully said. The "why" matters more than the "what".',
  'Echoing the others — well written and well argued.',
  'Hard agree. Especially the bit about ownership.',
  'Thanks for putting this out there. Not enough people say this.',
  'Question: does this still hold for very small teams?',
  'The chart alone is worth a thousand meetings.',
  'You nailed it. The cost of complexity is almost always underestimated.',
  // Long, multi-paragraph
  'A long one from me:\n\nI have been thinking about this for a while and I think the core insight is that incentives shape behavior more than slogans do.\n\nWhen the org rewards velocity over reliability, no amount of "we care about quality" posters will move the needle.\n\nThanks for the post — sharing widely.',
  'Great points. Worth re-reading once a quarter.',
  'You are not wrong — but the devil is in the rollout.',
  'Solid. Sharing with my manager.',
  'This is one of the clearest takes I have seen on the topic.',
  '👀 this hit a little too close to home.',
  'Right on. The "shape of the org" angle is underexplored.',
  'Thanks for naming the elephant in the room.',
];

export const FAKE_SHARES = [
  // Single line
  'New blog post is up — would love your thoughts.',
  // Multi-line + quotes (mimics LinkedIn paragraph-per-line style)
  '"Reliability is a property of the system, not a feature you can add later."\n\nThree things I have learned the hard way:\n\n- Architecture matters more than tooling.\n- Ownership matters more than process.\n- Culture matters more than both.\n\nFull post in the comments.',
  'Excited to share that I will be speaking at a community meetup next month. 🎤',
  '"What gets measured gets managed" — but only if you measure the right thing.\n\nMore in the comments.',
  'Quick reminder that the best documentation is the one that gets read.',
  'TIL: most "outages" are actually misconfiguration in disguise. 🙃',
  'New essay: "The cost of clever code" — link in the first comment.',
  // Long with quotes and emoji
  '"Boring technology wins."\n\nI have been thinking about this a lot. Every time a team picks the shiny option, the on-call rotation pays the price six months later.\n\nIf in doubt, pick the boring thing. 🛠️',
  'Hiring! We are looking for a senior engineer who cares about reliability. DMs open.',
  'Just published part 2 of the series — would love feedback.',
  'Hot take: "platform team" is often code for "central bottleneck". Discuss. 🍿',
  'A small library I wrote over the weekend — hope it is useful to someone.',
  'Reposting this because it deserves a wider audience.',
  '"You can have it fast, cheap, or reliable — pick two." Still true in 2026.',
  "Slides from yesterday's talk are now public.",
];

export const FAKE_RECOMMENDATIONS = [
  'Working with this person was a genuine pleasure. They bring sharp thinking, calm execution, and a refreshing willingness to challenge assumptions. Any team would be lucky to have them.',
  'A rare combination of deep technical skill and strong communication. I have seen them turn fuzzy problems into clear plans more times than I can count. Highly recommended.',
  'One of the most thoughtful engineers I have worked with. They lead by example, lift others up, and never settle for "good enough" when something better is within reach.',
  'I would happily work with this person again. They are pragmatic, patient, and great at building trust across teams.',
  'Few people combine technical depth and people skills the way they do. They make hard problems look approachable and complex systems feel understandable.',
  'They consistently raise the bar of every team they join. Strong opinions, loosely held, and always grounded in evidence.',
  'Excellent communicator and a steady hand under pressure. I learned a lot from our time working together.',
  'A natural mentor. They have a way of asking the right question at the right time, which is a skill that cannot be taught.',
];

export const FAKE_POSITION_DESCRIPTIONS = [
  '• Led platform engineering initiatives across multiple product teams.\n• Improved reliability practices and on-call processes.\n• Coached senior engineers and engineering managers.',
  '• Designed and built backend services for a high-traffic consumer product.\n• Owned end-to-end delivery from architecture to production rollout.',
  '• Founding engineer responsible for early product architecture and team scaling.\n• Established engineering culture and core tooling.',
  '• Drove cross-team alignment on observability standards.\n• Authored internal RFCs adopted across the organization.',
];

export const FAKE_HEADLINES = [
  'Engineering leader focused on reliability and developer experience',
  'Staff Engineer | Platforms, SRE, and humane on-call',
  'Builder. Mentor. Occasional writer.',
];

export const FAKE_SUMMARY =
  'Engineer with experience across platforms, reliability, and developer tooling. I enjoy turning messy problems into simple systems, and I write occasionally about the human side of engineering.';

export const FAKE_COMPANIES_FOR_PEOPLE = [
  'Acme Corp',
  'Globex',
  'Initech',
  'Umbrella Labs',
  'Hooli',
  'Vandelay Industries',
  'Wayne Enterprises',
  'Stark Industries',
  'Wonka Inc',
  'Pied Piper',
];
